In [27]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
import pandas as pd
import joblib

In [28]:
data = pd.read_csv("house.csv")
data.head()

area_sqft  num_bedrooms  num_bathrooms  age          price
0  2248.357077             4              3   23  357271.970790
1  1930.867849             1              3   21  294558.190925
2  2323.844269             3              1    0  392213.200637
3  2761.514928             5              3   17  469463.904947
4  1882.923313             3              3    5  331045.288653

In [29]:
X = data.drop('price', axis=1)
X.head()

area_sqft  num_bedrooms  num_bathrooms  age
0  2248.357077             4              3   23
1  1930.867849             1              3   21
2  2323.844269             3              1    0
3  2761.514928             5              3   17
4  1882.923313             3              3    5

In [30]:
Y = data['price']
Y.head()

0    357271.970790
1    294558.190925
2    392213.200637
3    469463.904947
4    331045.288653
Name: price, dtype: float64

In [31]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
x_train.shape, y_train.shape

((800, 4), (800,))

In [32]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [33]:
predictions = model.predict(x_test)
predictions

array([340230.97274702, 398287.48231711, 179821.47193381, 298056.548642  ,
       231879.89637343, 398471.0907615 , 274685.6762683 , 216278.23015324,
       365079.74373988, 280016.39495361, 284380.80991401, 328172.51644355,
       410556.90561904, 295634.47344343, 373312.19926314, 259957.9460946 ,
       325547.25657271, 409939.80322115, 359822.66109595, 325118.95047723,
       312912.08789331, 357431.17226898, 347019.21011537, 333815.78904352,
       352783.28556754, 394853.57656575, 272586.04632336, 444819.8013489 ,
       317110.72534084, 270795.10396859, 215953.79706917, 263384.34356298,
       343301.18826759, 242319.93465977, 317605.65042637, 301837.67286004,
       282765.05979778, 346933.69656156, 321707.89236731, 398104.99382199,
       346795.73838791, 357722.02263297, 393032.78645839, 295039.81269516,
       363065.44152674, 290998.92967405, 393226.25468644, 254560.18389226,
       297319.34911633, 274029.90427374, 322216.33496179, 412592.31523235,
       330871.10416714, 2

In [34]:
mse = mean_squared_error(y_test, predictions)
mse

100136123.89556034

In [35]:
r2 = r2_score(y_test, predictions)
r2

0.9819234822019186

In [36]:
model.coef_

array([  149.90409627,  9676.53840028,  6691.9184065 , -1165.42878636])

In [37]:
model.intercept_

757.3421147078043

In [38]:
data.head()

area_sqft  num_bedrooms  num_bathrooms  age          price
0  2248.357077             4              3   23  357271.970790
1  1930.867849             1              3   21  294558.190925
2  2323.844269             3              1    0  392213.200637
3  2761.514928             5              3   17  469463.904947
4  1882.923313             3              3    5  331045.288653

In [39]:
test_data = np.array([[2248.357077, 4, 3, 23]])
predictions = model.predict(test_data)
predictions

c:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([369772.32455837])

In [40]:
joblib.dump(model, 'house_price_model.pkl')

['house_price_model.pkl']